### ISSUE TITLE
轮播表悬浮问题

### ISSUE THREAD

**Issue by zb1908** [DataV-Team/DataV#106]
#### 出现Bug的组件？
轮播表

#### 组件配置数据？

hoverPause:true

#### 期望情况？
鼠标悬浮轮播停止
#### 实际情况？
悬浮轮播不停止
#### 其他相关信息

- DataV版本   2.8.4
- 浏览器版本   firefox 77.0.1    Chromium Edge 85.0
- 其他

**Comment by chen-i** [comment]
hoverPause不是写在config里面，写在组件上
<dv-scroll-board :config="config" :hoverPause="true" />

**Comment by jiaming743** [comment]
`v2.9.0`添加的这个属性，请更新至最新版本
