### ISSUE TITLE
dv-scroll-board组件使用hoverPause 悬停暂停轮播属性 没效果

### ISSUE THREAD

**Issue by liangluo** [DataV-Team/DataV#107]
## Bug report
使用hoverPause 悬停暂停轮播属性，无法暂停，
#### 出现Bug的组件？
dv-scroll-board

#### 期望情况？
设置hoverPause为true时，鼠标悬停 停止整页轮播

#### 其他相关信息

- DataV版本  
- 浏览器版本
- 其他

**Comment by chen-i** [comment]
可以暂停呀

**Comment by jiaming743** [comment]
是最新版？

**Comment by jiaming743** [comment]
`v2.9.0`添加的这个属性，请更新至最新版本

**Comment by dengsuchuan** [comment]
啊啊啊，没用找到文档，官网只说可以绑定事件，没说怎么绑定

**Comment by JKing8396** [comment]
dv-scroll-board组件使用hoverPause会卡死

**Comment by JKing8396** [comment]
dv-scroll-board组件在1.1.3之后使用hoverPause会卡死
