### ISSUE TITLE
dv-digital-flop 数字为 0 的时候 数字会不显示

### ISSUE THREAD

**Issue by chen-i** [DataV-Team/DataV#108]
#### 出现Bug的组件？
dv-digital-flop

#### 其他相关信息

- DataV版本
2.9.2
- 浏览器版本
- 其他
刚发现 图表里面的仪表盘也不显示 0 

![image](https://user-images.githubusercontent.com/37339618/85354214-a50d5100-b53c-11ea-98ee-1c33c9c5f819.png)

` series: [
          {
            type: "gauge",
            startAngle: -Math.PI / 2,
            endAngle: Math.PI * 1.5,
            arcLineWidth: 10,
            data: [
              {
                name: "itemA",
                value: percent,   
                gradient: ["#03c2fd", "#1ed3e5", "#2fded6"]
              }
            ],
            axisLabel: {
              show: false
            },
            axisTick: {
              show: false
            },
            pointer: {
              show: false
            },
            dataItemStyle: {
              lineCap: "round"
            },
            details: {
              show: true,
              formatter: "{value}%",
              style: {
                fill: "#1ed3e5",
                fontSize: 36
              }
            }
          }
        ]`

   value: percent,  percent为0是也不显示数字0

**Comment by xueyj123** [comment]
同问，也是碰到这个问题了

**Comment by jiaming743** [comment]
已修复，升级至`v2.9.3`即可，参见[v2.9.3](https://github.com/DataV-Team/DataV/releases/tag/V2.9.3-alpha)
