### ISSUE TITLE
vue 内存泄漏

### ISSUE THREAD

**Issue by HoHoYee** [DataV-Team/DataV#110]
页面挂着太久，导致浏览器占用很大得电脑内存，关掉浏览器才释放掉

**Comment by jiaming743** [comment]
是最新版的吗？都用了哪些组件

**Comment by sonicsunsky** [comment]
我也遇到cpu占用高的问题了，macos系统+chrome浏览器，打开一会感觉就很卡

**Comment by ErricLu** [comment]
这个问题太严重了，开发要维护啊，现在真是后悔死用这个了，真是cpu GPU 内存占用都高，主要是还不释放

**Comment by jackchenyang** [comment]
网页放至一个晚上就会内存溢出，有什么优化方案？
