### ISSUE TITLE
飞线图是否可以提供飞线反向流动,很多场景都是反向流动

### ISSUE THREAD

**Issue by saesxiao** [DataV-Team/DataV#12]
#### 这个特性解决了什么问题？
飞线图只能从散点飞向中心点，实际上很多需求是反向的，还有多中心点需求。

#### 这个特性的实现形式？
新增配置项

**Comment by net592** [comment]
确实是有这种需求场景

**Comment by LFL398619091** [comment]
这种需求场景挺多的

**Comment by jiaming743** [comment]
在`@jiaminghi/data-view@2.7.0`中新增**飞线图增强版**，可以配置任意两点间飞线，精细化配置飞线和飞线点，由于配置项冲突，所以新增该组件，在**3.x**中将替换原有飞线图。参见[release](https://github.com/DataV-Team/DataV/releases/tag/V2.7.0-alpha)。
