### ISSUE TITLE
datav 引入列表轮播数据报错的问题

### ISSUE THREAD

**Issue by ZhongHongLi** [DataV-Team/DataV#125]
vue.esm.js?efeb:628 [Vue warn]: Error in beforeDestroy hook: "TypeError: domObserver.disconnect is not a function"

found in

---> <DvScrollBoard> at node_modules/@jiaminghi/data-view/lib/components/scrollBoard/src/main.vue
       <SuperviseR> at src/view/submodule/inSupervise/superviseR.vue
         <Index> at src/view/submodule/inSupervise/index.vue
           <Index> at src/view/layout/index.vue
             <App> at src/App.vue
               <Root>

**Comment by jiaming743** [comment]
请升级至最新版，已优化此处
