### ISSUE TITLE
updateRows方法

### ISSUE THREAD

**Issue by 517724473** [DataV-Team/DataV#127]
这个方法给个例子 也不知道写在哪里在vue中，很懵的 老大

**Comment by jiaming743** [comment]
```vue
<dv-scroll-board :config="config" ref="scroll-board"  />

export default {
   doUpdate () {
      const scrollBoard = this.$refs['scroll-board']
      scrollBoard.updateRows(someRows)
  }
}
```

**Comment by 517724473** [comment]
老大 可以具体些不 看的有点麻

**Comment by 517724473** [comment]
methods: {
  
    doUpdate () {
      const scrollBoard = this.$refs['scroll-board']
      scrollBoard.updateRows( ['<div style="text-align: center;font-size: calc(12px + (16 - 12) * ((100vw - 400px) / (1500 - 400)));">455012157133761</div>',
        ])
    }
  },

**Comment by 517724473** [comment]
TypeError: scrollBoard.updateRows is not a function

**Comment by BZ-koko** [comment]
跟新datav库到最新版本，或者updateRows的版本

**Comment by BZ-koko** [comment]
遇到了同样的问题，datav是最新版本

**Comment by 517724473** [comment]
感谢搞定


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Tony <notifications@github.com&gt;
发送时间: 2020年8月19日 16:59
收件人: DataV-Team/DataV <DataV@noreply.github.com&gt;
抄送: 517724473 <517724473@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[DataV-Team/DataV] updateRows方法 (#127)





 
跟新datav库到最新版本，或者updateRows的版本

**Comment by jiaming743** [comment]
请确保版本大于等于`v2.9.6`
参考下述🌰
```vue
<!DOCTYPE html>
<html>
  <head>
    <title>DataV</title>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/@jiaminghi/data-view/dist/datav.map.vue.js"></script>
    <style>
      html,
      body,
      #app {
        width: 100%;
        height: 100%;
        margin: 0px;
        padding: 0px;
      }

      .dv-scroll-board {
        width: 400px !important;
        height: 200px !important;
      }
    </style>
  </head>
  <body>
    <div id="app">
      <dv-scroll-board :config="config" ref="test"></dv-scroll-board>
    </div>

    <script>
      var app = new Vue({
        el: "#app",
        data() {
          return {
            config: {
              header: ["列1", "列2", "列3"],
              data: [
                ["行1列1", "行1列2", "行1列3"],
                ["行2列1", "行2列2", "行2列3"],
              ],
            },
          };
        },
        mounted() {
          setTimeout(() => {
            this.$refs["test"].updateRows([
              ["行1列1", "行1列2", "行1列3"],
              ["行2列1", "行2列2", "行2列3"],
              ["行3列1", "行3列2", "行3列3"],
              ["行4列1", "行4列2", "行4列3"],
              ["行5列1", "行5列2", "行5列3"],
              ["行6列1", "行6列2", "行6列3"],
              ["行7列1", "行7列2", "行7列3"],
              ["行8列1", "行8列2", "行8列3"],
              ["行9列1", "行9列2", "行9列3"],
              ["行10列1", "行10列2", "行10列3"],
            ]);
          }, 2000);
        },
      });
    </script>
  </body>
</html>
```

**Comment by 517724473** [comment]
谢谢 老大 我搞定了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: JM <notifications@github.com&gt;
发送时间: 2020年8月19日 17:48
收件人: DataV-Team/DataV <DataV@noreply.github.com&gt;
抄送: 517724473 <517724473@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[DataV-Team/DataV] updateRows方法 (#127)





 
请确保版本大于等于v2.9.6
 参考下述🌰
 <!DOCTYPE html&gt; <html&gt;   <head&gt;     <title&gt;DataV</title&gt;     <script src="https://unpkg.com/vue"&gt;</script&gt;     <script src="https://unpkg.com/@jiaminghi/data-view/dist/datav.map.vue.js"&gt;</script&gt;     <style&gt;       html,       body,       #app {         width: 100%;         height: 100%;         margin: 0px;         padding: 0px;       }        .dv-scroll-board {         width: 400px !important;         height: 200px !important;       }     </style&gt;   </head&gt;   <body&gt;     <div id="app"&gt;       <dv-scroll-board :config="config" ref="test"&gt;</dv-scroll-board&gt;     </div&gt;     <script&gt;       var app = new Vue({         el: "#app",         data() {           return {             config: {               header: ["列1", "列2", "列3"],               data: [                 ["行1列1", "行1列2", "行1列3"],                 ["行2列1", "行2列2", "行2列3"],               ],             },           };         },         mounted() {           setTimeout(() =&gt; {             this.$refs["test"].updateRows([               ["行1列1", "行1列2", "行1列3"],               ["行2列1", "行2列2", "行2列3"],               ["行3列1", "行3列2", "行3列3"],               ["行4列1", "行4列2", "行4列3"],               ["行5列1", "行5列2", "行5列3"],               ["行6列1", "行6列2", "行6列3"],               ["行7列1", "行7列2", "行7列3"],               ["行8列1", "行8列2", "行8列3"],               ["行9列1", "行9列2", "行9列3"],               ["行10列1", "行10列2", "行10列3"],             ]);           }, 2000);         },       });     </script&gt;   </body&gt; </html&gt;

**Comment by willcom95** [comment]
有点坑, 用this.refs返回的数据格式变成一个数组了,后面要加个[0]才是组件实例
<dv-scroll-board :config="config" ref="scroll-board"  />

export default {
   doUpdate () {
      const scrollBoard = this.$refs['scroll-board'][0] // 注意看这里[0]
      scrollBoard.updateRows(someRows)
  }
}
