### ISSUE TITLE
排名轮播表建议给数值增加千位符格式属性

### ISSUE THREAD

**Issue by G-Maxx** [DataV-Team/DataV#129]
#### 这个特性解决了什么问题？
解决数据格式问题
#### 这个特性的实现形式？
为组件config增加新属性  numberFormat: true/false，true为千位符格式、false为原始值（默认false）；
或为组件config.data增加新属性  displayValue (实际显示值)  而data.value作为渲染值不显示；
个人拙见，具体实现方式作者为准。

**Comment by jiaming743** [comment]
[v2.9.8](https://github.com/DataV-Team/DataV/releases/tag/V2.9.8-alpha)新增`valueFormatter`属性

通过配置该属性即可任意格式化数值格式

详细说明参见官网[数值格式化](http://datav.jiaminghi.com/guide/scrollRankingBoard.html#%E6%95%B0%E5%80%BC%E6%A0%BC%E5%BC%8F%E5%8C%96)
