### ISSUE TITLE
IE11和andorid5白屏

### ISSUE THREAD

**Issue by shaochangxing** [DataV-Team/DataV#143]
能否兼容低版本浏览器，现在引入datav之后低版本浏览器直接异常白屏。

**Comment by jiaming743** [comment]
将组件库纳入babel编译看看转码后还有没有这个问题

**Comment by shaochangxing** [comment]
> 将组件库纳入babel编译看看转码后还有没有这个问题

有问题，vue/cli 4创建的项目默认引入babel，应该不用加额外的配置了吧。

**Comment by jiaming743** [comment]
[@vue/cli - Docs - transpileDependencies](https://cli.vuejs.org/zh/config/#transpiledependencies)

>transpileDependencies
>默认情况下 babel-loader 会忽略所有 node_modules 中的文件。如果你想要通过 Babel 显式转译一个依赖，可以在这个选项中列出来。

**Comment by 13250515751** [comment]
IE11和android 部分低版本webview不兼容，显示白屏

**Comment by 13250515751** [comment]
SCRIPT1003: 缺少 ':'

**Comment by habc0807** [comment]
@13250515751 你的问题解决了吗？目前也遇到了，尝试了很多方案都不行，等待你的回复

**Comment by shaochangxing** [comment]
> @13250515751 你的问题解决了吗？目前也遇到了，尝试了很多方案都不行，等待你的回复

记不太清了，好像是先安装cli-plugin-babel，然后在vue.config配置文件里加上transpileDependencies: ['@jiaminghi/data-view']。

**Comment by habc0807** [comment]
（加急）@shaochangxing cli-plugin-babel 你用的什么版本，帮忙查看下~ 我目前的版本`"@vue/cli-plugin-babel": "~4.5.0",` 

我在babel.config.js里的配置：
```
module.exports = {
	presets: [
	  '@vue/cli-plugin-babel/preset',
	  [
		'@babel/preset-env',
		{
		  useBuiltIns: 'entry'
		}
	  ]
	]
}
```

**Comment by shaochangxing** [comment]
版本是4.5.0
module.exports = {
  presets: [
    ***@***.***/cli-plugin-babel/preset'
  ]
}



***@***.***
 
发件人： 尤小小
发送时间： 2021-05-20 13:19
收件人： DataV-Team/DataV
抄送： 胃在烧; Mention
主题： Re: [DataV-Team/DataV] IE11和andorid5白屏 (#143)
***@***.*** cli-plugin-babel 你用的什么版本，帮忙查看下~ ***@***.***/cli-plugin-babel": "~4.5.0",
我在babel.config.js里的配置：
module.exports = {
	presets: [
	  ***@***.***/cli-plugin-babel/preset',
	  [
		***@***.***/preset-env',
		{
		  useBuiltIns: 'entry'
		}
	  ]
	]
}

**Comment by shaochangxing** [comment]
> （加急）@shaochangxing cli-plugin-babel 你用的什么版本，帮忙查看下~ 我目前的版本`"@vue/cli-plugin-babel": "~4.5.0",`
> 
> 我在babel.config.js里的配置：
> 
> ```
> module.exports = {
> 	presets: [
> 	  '@vue/cli-plugin-babel/preset',
> 	  [
> 		'@babel/preset-env',
> 		{
> 		  useBuiltIns: 'entry'
> 		}
> 	  ]
> 	]
> }
> ```

版本是4.5.0
module.exports = {
   presets: [
    '@vue/cli-plugin-babel/preset'
  ]
}
