### ISSUE TITLE
动态环图当页面切换到后台后会内存泄露，导致页面崩溃，chrome测试

### ISSUE THREAD

**Issue by chanbaihai** [DataV-Team/DataV#16]
#### 出现Bug的组件？
动态环图
#### 组件配置数据？

无特殊配置
#### 期望情况？
不会产生内存泄露
#### 实际情况？
实测切换后台后内存占用一直上升，最终导致网站崩溃
实测datav文档官网也存在相同问题，切换到动态环图文档，打开chrome devtool，memory选项，切换到其他tab页，js heap size一直在上升，若长时间后台则网页会崩溃
#### 其他相关信息

- DataV版本
- 浏览器版本
chrome
- 其他
![image](https://user-images.githubusercontent.com/36693835/65292267-466c0e80-db89-11e9-972c-c6c2e159eda1.png)

![image](https://user-images.githubusercontent.com/36693835/65292314-7fa47e80-db89-11e9-874f-c6d03388c91f.png)

**Comment by jiaming743** [comment]
情况确实，引起内存泄露的不是组件本身，而是因为依赖项`charts`本身缺陷，尽快修复

**Comment by jiaming743** [comment]
由于过于频繁的刷新图表状态，`CRender`插件动画池的动画数据持续增长（绘制速度赶不上消耗速度）导致内存堆积，已经做了相关优化（每次刷新图表强制清空动画池），请更新至`@jiaminghi/datav@2.4.6`，另外图表组件请勿过于频繁的刷新状态（刷新间隔小于3S），后期将针对性的优化插件，以取得更少的内存占用。
