### ISSUE TITLE
建议写一个类似用户可自由扩展的教程

### ISSUE THREAD

**Issue by modernzc** [DataV-Team/DataV#19]
这样可以丰富当前的组建库

**Comment by yizhiyuyou** [comment]
你好，能说的跟具体一些吗?我现在能想到的是把内部用到的mixin给导出。而内部依赖的chart本身也是一个单独的包，datav本身也是通过使用这个chart，创建了一些组件，给用户使用。

**Comment by modernzc** [comment]
很期待，更多的示例
