### ISSUE TITLE
谷歌浏览器内存消耗很大,导致页面崩溃。急求作者解决

### ISSUE THREAD

**Issue by luckilyhang** [DataV-Team/DataV#20]
#### 其他相关信息

- DataV版本
- 浏览器版本
- 其他

**Comment by jiaming743** [comment]
页面切到后台后 确实会内存泄露，前阵子出去旅游了，这两天有时间会先着手解决这个问题

**Comment by jiaming743** [comment]
内存泄露主要是动态环图有问题，涉及到底层的`CRender`和`Charts`插件，已经做了相关优化，请更新至`@jiaminghi/datav@2.4.6`，另外图表组件请勿过于频繁的刷新状态（刷新间隔小于3S），后期将针对性的优化插件，以取得更少的内存占用。
