### ISSUE TITLE
Vue3.0不支持template循环 

### ISSUE THREAD

**Issue by Verdicts-ye** [DataV-Team/DataV#208]
#### 出现Bug的组件？
decoration3和decoration6
#### 控制台错误输出？

编译错误    Internal server error: <template v-f
![微信截图_20210609165244](https://user-images.githubusercontent.com/50040175/121323905-cd0ae580-c942-11eb-8901-79c8554c0f8e.png)
![微信截图_20210609165259](https://user-images.githubusercontent.com/50040175/121323911-ce3c1280-c942-11eb-9b19-063791aef6db.png)

or> key should be placed on the <template> tag.
#### 期望情况？
期望情况正常运行。
#### 其他相关信息

- DataV版本
- 浏览器版本
- 其他

**Comment by ZhengXiaowei** [comment]
你把key放template标签上就好了 vue3 现在用template循环的话 key是放在template标签上的

**Comment by board-man** [comment]
分别修改 decoration3 和 decoration6 中对应报错的地方 /src/main.vue  5-24行， 把key放在template标签上，用空格分隔
<template
        v-for="(point, i) in points" :key="i"
      >
        <rect
          :fill="mergedColor[0]"
          :x="point[0] - halfPointSideLength"
          :y="point[1] - halfPointSideLength"
          :width="pointSideLength"
          :height="pointSideLength"
        >
          <animate
            v-if="Math.random() > 0.6"
            attributeName="fill"
            :values="`${mergedColor.join(';')}`"
            :dur="Math.random() + 1 + 's'"
            :begin="Math.random() * 2"
            repeatCount="indefinite"
          />
        </rect>
      </template>

**Comment by huangxuelun** [comment]
同问，难道不计划支持vue3吗？
