### ISSUE TITLE
轮播表是否支持控制表头某个字段显示隐藏

### ISSUE THREAD

**Issue by leepule** [DataV-Team/DataV#21]

**Comment by jiaming743** [comment]
请描述的更具体点？

**Comment by leepule** [comment]
![image](https://user-images.githubusercontent.com/16642691/68440647-b8b2b400-0206-11ea-8a80-ded3cba5b68a.png)
可以控制某一列是不是隐藏

**Comment by jiaming743** [comment]
直接对数据源处理即可
