### ISSUE TITLE
import DataV之后，IE9内打开会报错，页面空白。

### ISSUE THREAD

**Issue by songchengxuan** [DataV-Team/DataV#22]
import DataV之后，IE9内打开会报错，页面空白。
显示的错误为“**script1003: 缺少 ':'** ”，经过排查，
发现确实是导入了这个包的原因，在谷歌浏览器中
则不存在类似问题。

**Comment by jiaming743** [comment]
限于能力和精力暂时没有兼容除谷歌外的其他浏览器，请使用Chrome浏览器：）
