### ISSUE TITLE
谷歌浏览器内存溢出崩溃的问题解决了么？

### ISSUE THREAD

**Issue by luckilyhang** [DataV-Team/DataV#24]
#### 其他相关信息

- DataV版本
- 浏览器版本
- 其他

**Comment by jiaming743** [comment]
已解决，更新至最新版本`V2.4.7`即可
参见Release [V2.4.6](https://github.com/DataV-Team/DataV/releases/tag/V2.4.6-alpha) [V2.4.7](https://github.com/DataV-Team/DataV/releases/tag/V2.4.7-alpha)
