### ISSUE TITLE
没有vue3版本吗？可惜组件比较好用 做大数据开发非常好

### ISSUE THREAD

**Issue by MaybeQHL** [DataV-Team/DataV#268]
没有vue3版本吗？可惜组件比较好用 做大数据开发非常好

**Comment by vaemusic** [comment]
可以看下这个 https://github.com/vaemusic/datav-vue3

**Comment by MaybeQHL** [comment]
> 可以看下这个 https://github.com/vaemusic/datav-vue3

好的谢谢
