### ISSUE TITLE
饼图某些数据比较小，密集会导致标注重合

### ISSUE THREAD

**Issue by cwzp990** [DataV-Team/DataV#29]
## Bug report
饼图当某些数据比较小，会导致标注线重合 
#### 出现Bug的组件？
chart.js  饼图
#### 期望情况？
需要像E-chart那样有一个配置项，标注不会重合
#### 实际情况？
![image](https://user-images.githubusercontent.com/33391266/69215108-bb68be00-0ba3-11ea-9b77-5ad9a06667fb.png)
#### 其他相关信息

- DataV版本
- 浏览器版本
- 其他

**Comment by jiaming743** [comment]
刚才你是不是加群了，手滑点拒绝了，不好意思哈，可以重新添加，这个问题因为算法有点问题，所以暂时没法避免重叠，后期将会优化，如果有紧急需求可以安装echarts，先使用echarts
