### ISSUE TITLE
有成品的演示地址吗？

### ISSUE THREAD

**Issue by zhongku** [DataV-Team/DataV#30]
有成品的演示地址吗？

**Comment by jiaming743** [comment]
有Demo演示和文档，你说的成品是什么

**Comment by zhongku** [comment]
![image](https://user-images.githubusercontent.com/16175495/69301825-7e0f3980-0c52-11ea-8ba8-0561994be6d4.png)
类似这类成品图标

**Comment by jiaming743** [comment]
http://datav.jiaminghi.com/demo/
