### ISSUE TITLE
我在用 排名轮播表 的时候，发现，我不想要自动排序，怎么办

### ISSUE THREAD

**Issue by ToMissYou** [DataV-Team/DataV#35]
我在用 排名轮播表 的时候，发现，我不想要自动排序，怎么办

**Comment by jiaming743** [comment]
更新至版本`@jiaminghi/data-view@2.6.0`即可
添加了新配置项`sort`，默认为`true`，设置为`false`即可关闭自动排序
参见[release](https://github.com/DataV-Team/DataV/releases/tag/V2.6.0-alpha)
