### ISSUE TITLE
排名轮播表data属性的name属性扩展

### ISSUE THREAD

**Issue by zooeydotmango** [DataV-Team/DataV#36]
## Feature request
多个值传入data子对象的name属性时可以对值添加样式或者标签
#### 这个特性解决了什么问题？
![image](https://user-images.githubusercontent.com/30279954/70969890-f5ac7900-20d7-11ea-928a-a7793a358e38.png)
可以在传入多个值时只对 文字/数字/分割符添加样式

**Comment by jiaming743** [comment]
更新至版本`@jiaminghi/data-view@2.6.0`即可
该版本使用`v-html`进行name的渲染 你可以通过传入html标签以实现个性化name标签
参见[release](https://github.com/DataV-Team/DataV/releases/tag/V2.6.0-alpha)
