### ISSUE TITLE
希望组件可以兼容Nuxt

### ISSUE THREAD

**Issue by anti996sz** [DataV-Team/DataV#38]
试图通过NuxtJS框架中通过[Plugin](https://nuxtjs.org/api/configuration-plugins#when-do-i-use-plugins-)注册DataV时来开发Web应用时，出现错误

import Vue from 'vue'
import dataV from '@jiaminghi/data-view'
Vue.use(dataV)

module "d:/9. we-covmee/gdcc-datav/node_modules/@jiaminghi/data-view/lib/index"
Could not find a declaration file for module '@jiaminghi/data-view'. 'd:/9. we-covmee/gdcc-datav/node_modules/@jiaminghi/data-view/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/jiaminghi__data-view` if it exists or add a new declaration (.d.ts) file containing `declare module '@jiaminghi/data-view';`ts(7016)
No quick fixes available

运行时错误：

SyntaxError
Unexpected token export

#### 这个特性解决了什么问题？
可以在NuxtJS中

#### 这个特性的实现形式？
不清楚

#### 是否愿意为此特性提交PR？
没有这个能力

**Comment by yizhiyuyou** [comment]
@anti996sz 没在 NUXT.js 中试过，但是从你的报错中可以看出，是因为没有找到 datav 的 typescript 类型声明文件。现在 datav 不是通过 typescript 写的。所以暂不支持 typescript。但是有计划支持。现在正在将底层的几个插件通过 typescript 重写。

**Comment by jiaming743** [comment]
@anti996sz 敬请期待TS版组件库的发布
