### ISSUE TITLE
typeScript好像无法使用

### ISSUE THREAD

**Issue by lubianniu** [DataV-Team/DataV#39]

**Comment by jiaming743** [comment]
Vue版暂时不支持TS，要等基础插件用TS重写后和Vue3.0发布 才会跟进发布Vue的TS版组件库

敬请期待

**Comment by MADAO-Chen** [comment]
新建一个.d.ts声明文件
`declare module '@jiaminghi/data-view' {
  export  const borderBox1: any
  export  const decoration5: any
  export  const decoration9: any
  export  const decoration8: any
  export  const capsuleChart: any
}`，这个是按需引入写法
