### ISSUE TITLE
排名轮播表

### ISSUE THREAD

**Issue by ningstudy** [DataV-Team/DataV#42]
## Bug report
排名轮播表动态更新数据后轮播不会从第一个开始轮播，而是从上一次轮播的地方继续轮播。。
而且更新数据时必须要以this.config={
data:[]
}
这样的方式才能更新，否则视图无变化
#### 组件配置数据？

config:{
data:[]
}
#### 其他相关信息

- DataV版本
- 浏览器版本
- 其他

**Comment by wzx-3015** [comment]
所有的参数均为深度监听  只有重新复制才会感知到
