### ISSUE TITLE
动态环图内的数字翻牌器不能设置两位小数

### ISSUE THREAD

**Issue by zooeydotmango** [DataV-Team/DataV#43]
#### 这个特性解决了什么问题？

希望能加一个配置项

**Comment by jiaming743** [comment]
更新至版本`@jiaminghi/data-view@2.7.2`，可通过**digitalFlopToFixed**配置小数位数，参见[release](https://github.com/DataV-Team/DataV/releases/tag/V2.7.2-alpha)。
