### ISSUE TITLE
动态环图内的数字翻牌器设置两位小数只显示xx.00%

### ISSUE THREAD

**Issue by zooeydotmango** [DataV-Team/DataV#44]
#### 出现Bug的组件？
dv-active-ring-chart

- DataV版本
2.7.2
- 浏览器版本
- 其他

**Comment by jiaming743** [comment]
已修复，请升级版本至`@jiaminghi/data-view@2.7.3` 参见[release](https://github.com/DataV-Team/DataV/releases/tag/V2.7.3-alpha)
