### ISSUE TITLE
IE有兼容性问题，demo直接在IE11打开空白

### ISSUE THREAD

**Issue by Alansherlock** [DataV-Team/DataV#46]
#### 出现Bug的组件？
http://datav.jiaminghi.com/demo/   iE直接打开控制台报错
#### 期望情况？
兼容IE，至少11
#### 其他相关信息

- DataV版本
引入DataV,npm包使用也会报错，npm包是最新的
- 浏览器版本
IE11
- 其他

**Comment by jiaming743** [comment]
不支持IE的，建议使用Chrome浏览器
