### ISSUE TITLE
是否可以配合echarts使用

### ISSUE THREAD

**Issue by Wu-1992** [DataV-Team/DataV#47]
配合echarts使用后，echarts图表如有多个，则不能正常显示或只能显示其中的一个图表，请问datav组件可以配合echarts使用吗？

**Comment by jiaming743** [comment]
可以，你描述的情况应该是datav组件没有获取到正确的宽高 导致没显示出来 可以在控制台查看dom节点的渲染情况

**Comment by Wu-1992** [comment]
<dv-border-box-10><div id="myChart" :style="{width: '300px', height: '300px'}"></div></dv-border-box-10>,控制台里看页面元素，div有大小，但是内容确显示不了

**Comment by Wu-1992** [comment]
控制台里看页面元素，div有大小，但是内容确显示不了<dv-border-box-10><div id="myChart" :style="{width: '300px', height: '300px'}"></div></dv-border-box-10>

**Comment by Wu-1992** [comment]
<dv-border-box-10><div id="myChart" :style="{width: '300px', height: '300px'}"></div></dv-border-box-10>,

**Comment by Wu-1992** [comment]
`<dv-border-box-10><div id="myChart" :style="{width: '300px', height: '300px'}"></div></dv-border-box-10>,`检查元素时div有正常宽高，但是内容确显示不了

**Comment by jiaming743** [comment]
如果要使用边框组件 建议将需要放置在边框内的内容单独封装成组件 这样比较容易避免这种情况出现

before
```html
<dv-border-box-10>
  <div ref="chart' class="chart"></div>
</dv-border-box-10>
```

after
```html
<dv-border-box-10>
  <component-a></component-a>
</dv-border-box-10>

<!--component-a-->
<template>
  <div class="container">
    <div ref="chart' class="chart"></div>
  </div>
</template>

// style
.container, .chart {
  width: 100%;
  height: 100%
}
```

**Comment by sunyd1006** [comment]
有效度：楼上说得对，建议封装组件，我试过有效。
疑问：这是什么原理的，为什么封装成组件就能够很好的避免这种情况呢？

**Comment by sunyd1006** [comment]
<dv-border-box-10>
  <div v-show="!a">
      <component-a></component-a>
 </div>

<div v-show="a">
      
     <button @click="改变a的值>点击显示组件compnent-a</button>
 </div>
  
</dv-border-box-10>

**Comment by sunyd1006** [comment]
<dv-border-box-10>
   <div v-show="a>
       <component-a></component-a>
   </div>
  
  
  <div v-show="!a">
     
     <button @click="让a的值等于1的方法>显示component-a</b/utton>
  </div>
</dv-border-box-10>


<template>
  <div class="container">
    <div ref="chart' class="chart"></div>
  </div>
</template>

// style
.container, .chart {
  width: 100%;
  height: 100%
}

**Comment by sunyd1006** [comment]
<dv-border-box-10>
   <div v-show="a>
       <component-a></component-a>
   </div>
  
  
  <div v-show="!a">
     
     <button @click="让a的值等于1的方法>显示component-a</b/utton>
  </div>
</dv-border-box-10>


<template>
  <div class="container">
    <div ref="chart' class="chart"></div>
  </div>
</template>

// style
.container, .chart {
  width: 100%;
  height: 100%

**Comment by jiaming743** [comment]
echarts实例化时会获取dom宽高 当前页面mounted时 边框组件的slot插槽尚未渲染完毕 此时获取DOM宽高可能有误 封装成组件后 组件内的mounted函数被调用时 组件的父组件及祖先组件应当已经渲染完毕 此时可以避免获取宽高异常的情况 这只是我一种猜测

**Comment by hsw409328** [comment]
> echarts实例化时会获取dom宽高 当前页面mounted时 边框组件的slot插槽尚未渲染完毕 此时获取DOM宽高可能有误 封装成组件后 组件内的mounted函数被调用时 组件的父组件及祖先组件应当已经渲染完毕 此时可以避免获取宽高异常的情况 这只是我一种猜测

这个是真的大坑，用原生 dom都获取不到节点..

**Comment by hsw409328** [comment]
> echarts实例化时会获取dom宽高 当前页面mounted时 边框组件的slot插槽尚未渲染完毕 此时获取DOM宽高可能有误 封装成组件后 组件内的mounted函数被调用时 组件的父组件及祖先组件应当已经渲染完毕 此时可以避免获取宽高异常的情况 这只是我一种猜测

nextTick 理论上来说这个是可以的，但是贵组件不知道如何封装的，连这个方法都无效
