### ISSUE TITLE
轮播表会带动页面滚动？

### ISSUE THREAD

**Issue by peanutguo** [DataV-Team/DataV#52]
#### 出现Bug的组件？
轮播表
#### 组件配置数据？

官方实例
#### 控制台错误输出？

官方实例这个轮播表
http://datav.jiaminghi.com/guide/scrollBoard.html#%E5%9F%BA%E6%9C%AC%E8%BD%AE%E6%92%AD%E8%A1%A8
页面下边缘位置在轮播表里时 轮播表滚动会带动页面滚动

**Comment by wzx-3015** [comment]
请提供示例  目前官方示例没有此问题

**Comment by PL-FE** [comment]
我也遇到个问题，有空的时候帮忙研究下
源码：https://codesandbox.io/p/sandbox/zealous-leftpad-zpmdq3?file=/src/App.vue:11,59
预览：https://zpmdq3-5173.csb.app/#target
