### ISSUE TITLE
边框类型里的1和10类型并没有混入initWH这个方法

### ISSUE THREAD

**Issue by zfy-ql** [DataV-Team/DataV#53]
我在使用边框部分时，需要调用initWH()方法，但我发现边框类型里的1和10类型并没有混入这个方法，这是为什么

**Comment by jiaming743** [comment]
这两个边框的自适应只用了css，它们对DOM宽高的具体数值并不关心，所以就没引入，这个我忘记在文档写了，稍后会更新下文档

**Comment by jiaming743** [comment]
为了配置背景色，现在这俩组件也有这个方法了

**Comment by 441455201** [comment]
initWH()如何调用

**Comment by 441455201** [comment]
请教一下这个边框组件如何调用initWH方法

**Comment by 2448795365** [comment]
this.$refs.box.initWH()

**Comment by 2448795365** [comment]
给box取一个ref值，例如：dv-border-box-11 ref="box"，然后调用this.$refs.box.initWH() 就可以了

**Comment by songhuibing** [comment]
> 这两个边框的自适应只用了css，它们对DOM宽高的具体数值并不关心，所以就没引入，这个我忘记在文档写了，稍后会更新下文档

那该怎么调整边框的宽度呢

**Comment by songhuibing** [comment]
> 请教一下这个边框组件如何调用initWH方法

能告诉我你后面是怎么调整宽度的吗

**Comment by passparty** [comment]
> > 请教一下这个框架组件如何调用initWH方法
> 
> 能告诉我你是怎么调整宽度的吗

可以给box定义class值border-box-content和diy-box，  例如： dv-border-box-11 class="border-box-content  diy-box"，diy-box为box自定义css样式。不知道是否有更好方法，参考DataV文档http://datav.jiaminghi.com/guide/borderBox.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2

**Comment by 18844456160** [comment]
> 请教这个方法是如何调用initWH



> 

我调用了 但是显示undefand 是什么原因啊?
