### ISSUE TITLE
胶囊柱图在value最大值小于5时会渲染错误

### ISSUE THREAD

**Issue by NorthCrow** [DataV-Team/DataV#59]
dataV版本:2.3.7
横坐标数据渲染出错,而且数据长度也对不上
![image](https://user-images.githubusercontent.com/45928838/77048012-b6583600-6a00-11ea-9fae-07fbb2a1b6c1.png)
页面代码
![image](https://user-images.githubusercontent.com/45928838/77048109-df78c680-6a00-11ea-8c57-5e2ee5b48116.png)
配置代码
![image](https://user-images.githubusercontent.com/45928838/77048179-fd462b80-6a00-11ea-8500-b2ac61adf269.png)
--------------------------------------
value增加到5之后渲染正常
![image](https://user-images.githubusercontent.com/45928838/77048543-970dd880-6a01-11ea-8123-a8d890671c63.png)
![image](https://user-images.githubusercontent.com/45928838/77048596-adb42f80-6a01-11ea-9979-d53584c4eb08.png)
-------------------------------------
猜测可能是横坐标坐标算法是获取最大值后除5然后向上取整,结果最大值不足5,所以造成渲染错误

**Comment by wzx-3015** [comment]
**感谢您的反馈** 
目前已定位问题  正在修复
