### ISSUE TITLE
异步获取数据后，如何刷新图表

### ISSUE THREAD

**Issue by costaq** [DataV-Team/DataV#62]
异步获取数据后，data重新赋值，但图标并没有刷新，可以手动控制图标刷新吗

**Comment by costaq** [comment]
![code](https://user-images.githubusercontent.com/24690993/77385554-6b08a380-6dc3-11ea-8a27-0776fc060977.png)

根据文档中所写，重新生成新的props也没有用，是哪里写错了吗

**Comment by costaq** [comment]
![code](https://user-images.githubusercontent.com/24690993/77385722-e5d1be80-6dc3-11ea-94ec-8192efd4e2c2.png)

刚截图错了，看这个

**Comment by costaq** [comment]
已发现问题

**Comment by xutianting** [comment]
> 已发现问题
想问下怎么解决的

**Comment by jiaming743** [comment]
@xutianting 你也遇见不能刷新的问题？

**Comment by xutianting** [comment]
> @xutianting 你也遇见不能刷新的问题？

我现在遇到，，charts折线图会渲染出两个。。。

**Comment by xutianting** [comment]
> @xutianting 你也遇见不能刷新的问题？

反馈群群号是多少。。我想进

**Comment by xutianting** [comment]
@jiaming743 想进反馈群
