### ISSUE TITLE
series数据更新问题

### ISSUE THREAD

**Issue by costaq** [DataV-Team/DataV#63]
![code](https://user-images.githubusercontent.com/24690993/77392568-39e59e80-6dd6-11ea-95eb-b10e26af5340.png)

series 数组如何更新为新的，要替换data值

**Comment by jiaming743** [comment]
```javascript
this.lineOption.series[x].data = xxxx; this.lineOption = { ...this.lineOption }
```

**Comment by costaq** [comment]
> ```js
> this.lineOption.series[x].data = xxxx; this.lineOption = { ...this.lineOption }
> ```

我试过，还是报错
![image](https://user-images.githubusercontent.com/24690993/77398145-e6794d80-6de1-11ea-8596-d1f93f365b08.png)

![image](https://user-images.githubusercontent.com/24690993/77398161-f2650f80-6de1-11ea-8fb0-63ca866b4ce4.png)
