### ISSUE TITLE
可以提供直接import组件的方式吗，用于局部注册组件？

### ISSUE THREAD

**Issue by yoyogis** [DataV-Team/DataV#64]
#### 这个特性解决了什么问题？
局部引入组件，避免全局引入

#### 这个特性的实现形式？
将组件直接export

#### 是否愿意为此特性提交PR？
yes

**Comment by jiaming743** [comment]
可以，引入方式如下

`import borderBox1 from '@jiaminghi/data-view/lib/components/borderBox1/src/main.vue'`
