### ISSUE TITLE
期望动态环图增加具体数值显示

### ISSUE THREAD

**Issue by costaq** [DataV-Team/DataV#67]
#### 这个特性解决了什么问题？

环图可显示具体数值

#### 这个特性的实现形式？

增加可选参数，显示具体数值还是百分数

**Comment by jiaming743** [comment]
可通过配置`showOriginValue `显示具体数值

具体参见官网[配置](http://datav.jiaminghi.com/guide/activeRingChart.html#config%E5%B1%9E%E6%80%A7)
