### ISSUE TITLE
dv-border-box-11组件填充和囊图数值错误问题

### ISSUE THREAD

**Issue by NameWjp** [DataV-Team/DataV#68]
#### 这个特性解决了什么问题？
需求边框需要填充颜色

#### 这个特性的实现形式？
添加fill属性，覆盖 polyline 元素的fill 属性

#### 是否愿意为此特性提交PR？
是

另外有几个问题
1.我拉下代码后，打包会报错，查了下 rollup 没有安装，为什么 rollup 不安装到 devDependencies 里呢？
2.囊图数值错误
![image](https://user-images.githubusercontent.com/32758131/79406178-f17e6280-7fc8-11ea-9c3d-a1742a965633.png)
![image](https://user-images.githubusercontent.com/32758131/79406291-3f936600-7fc9-11ea-8850-aa16a930ae95.png)
![image](https://user-images.githubusercontent.com/32758131/79406306-4fab4580-7fc9-11ea-8d46-de06e6f22cce.png)

这里用了 set 后，v-for 循环出来的第一个元素是数组，显示错误，目前的是把 new Set 删除重新打包。

**Comment by jiaming743** [comment]
本身支持的color颜色配置不能满足需求嘛？

**Comment by NameWjp** [comment]
@jiaming743 不一样呀
before
![image](https://user-images.githubusercontent.com/32758131/79408384-c5191500-7fcd-11ea-909a-220c90ee835d.png)
after
![image](https://user-images.githubusercontent.com/32758131/79408395-cd715000-7fcd-11ea-80ef-d95804acfeba.png)
实心和空心的区别

**Comment by jiaming743** [comment]
这个填充色的可以增添一个配置项，给所有的边框都提供背景色支持

至于你说的使用Set后label输出异常，我这里没有复现出来，请提供一下更多细节比如vue版本之类的，Vue的v-for对Set之类的数据类型是使用遍历器接口进行遍历的，应该是不会出现那种情况

rollup这种工具一般都是全局安装，所以我也就没写到devDep里

**Comment by NameWjp** [comment]
@jiaming743 
![image](https://user-images.githubusercontent.com/32758131/79409889-92711b80-7fd1-11ea-8562-4832dde03ab6.png)

查了下文档，2.6版本后才支持原生的 Map 和 Set，我这边是2.5x的版本，应该是版本的问题。

**Comment by jiaming743** [comment]
下个版本做个兼容，和那个背景色一块发
