### ISSUE TITLE
不兼容IE吗

### ISSUE THREAD

**Issue by JianLinWei1** [DataV-Team/DataV#70]
删除组件能用IE打开，引用后连项目都开不了

**Comment by jiaming743** [comment]
不兼容的，如果是项目打不开了，应该是因为库没有转Es5，可以在项目的编译配置里，把组件库纳入babel编译，就不会出现这种问题了，但是可能会有一些其他的问题，比如样式异常等。

**Comment by JianLinWei1** [comment]
> 不兼容的，如果是项目打不开了，应该是因为库没有转Es5，可以在项目的编译配置里，把组件库纳入babel编译，就不会出现这种问题了，但是可能会有一些其他的问题，比如样式异常等。

h好的 3Qu
