### ISSUE TITLE
老大 有个问题 关于背景色方面

### ISSUE THREAD

**Issue by yinshaoqian** [DataV-Team/DataV#73]
在使用DataV边框 当做提示框或弹出框的时候 一些异性边框设置了背景色之后会出现左上角或者右上角等不同角度 出现 背景色溢出
是否能有针对性性解决方案

**Comment by jiaming743** [comment]
争取明天发一个新版本，添加个新属性用来设置背景色，解决这个背景色溢出的问题，之前已经有这个feature的考虑了。

**Comment by jiaming743** [comment]
升级至`@jiaminghi/data-view@2.8.0`即可配置边框背景色

详情参见[自定义颜色](http://datav.jiaminghi.com/guide/borderBox.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2)
