### ISSUE TITLE
动态环图中数据为0.xx%时的环的大小不对

### ISSUE THREAD

**Issue by wang4978** [DataV-Team/DataV#74]
## Bug report
动态环图中数据为0.xx%时的环的大小不对。
如图中0.10%的环跟3.45%的差不多
![image](https://user-images.githubusercontent.com/3690572/80181748-08abf880-8638-11ea-9b18-211122250d0b.png)

![image](https://user-images.githubusercontent.com/3690572/80181792-19f50500-8638-11ea-9b7d-ba0a52c105f1.png)

#### 出现Bug的组件？
动态环图

#### 组件配置数据？

`config: {
        data: [
          {
            name: '周口',
            value: 16984
          },
          {
            name: '南阳',
            value: 48872
          },
          {
            name: '西峡',
            value: 17366
          },
          {
            name: '驻马店',
            value: 6101
          },
          {
            name: '新乡',
            value: 3197
          },
          {
            name: '郑州',
            value: 97
          }
        ],
        showValue: true,
        fontSize: 14,
        digitalFlopToFixed: 2
      }
`
#### 期望情况？
期望环形部分，0.xx% 的是实际分配的大小
#### 实际情况？
0.xx%的环形部分和3.xx%的大小差不多

#### 其他相关信息

- DataV版本
- 浏览器版本
- 其他

**Comment by jiaming743** [comment]
更新至最新版本即可，确保其依赖`@jiaminghi/charts`的版本为`0.2.15`或以上
如使用UMD版本，请重新拉取UMD文件
