### ISSUE TITLE
关于轮播表 边框的问题

### ISSUE THREAD

**Issue by cx741041875** [DataV-Team/DataV#77]
作者您好、我想请问一下关于这个轮播表 怎么添加边框(列边框) 类似于element的border属性
因为不知道该提哪个模块所以提到新特性建议里面了 - -。

**Comment by cx741041875** [comment]
![表格](https://user-images.githubusercontent.com/48713520/80670399-506bcd80-8ad9-11ea-9777-8b132415432f.png)

**Comment by jiaming743** [comment]
暂时没这个配置 不过可以加一个border配置，如果现在需要的话 可以考虑用css去选中格子 添加border样式

**Comment by cx741041875** [comment]
> 暂时没这个配置不过可以加一个边框配置，如果现在需要的话可以考虑用css去替换格子添加边框样式

谢谢回复 那就只能先通过css去加了
