### ISSUE TITLE
用边框组件dv-border-box-8  不设置宽度   右border没有显示 必须F12 拉拽一下才显示   

### ISSUE THREAD

**Issue by wcxdandan** [DataV-Team/DataV#94]
用边框组件dv-border-box-8  不设置宽度   右border没有显示 必须F12 拉拽一下才显示  
有什么解决办法吗

**Comment by wcxdandan** [comment]
必须设置具体的 width 吗？

**Comment by jiaming743** [comment]
百分比设置也是可以的，通常这种情况是组件没办法获取到父容器的宽高导致的，这个以后会优化，暂时的解决方案是 手动调用组件的`initWH`方法强制刷新宽高，或者组件绑定key值，刷新key值时销毁组件并重新渲染。文档有具体说明，可以参考
