### ISSUE TITLE
轮播表新增鼠标移入停止滚动，并且讲鼠标位置的数据抛出去的事件

### ISSUE THREAD

**Issue by knightgao** [DataV-Team/DataV#97]
#### 这个特性解决了什么问题？
1.新增鼠标移入停止滚动
2.抛出鼠标所在位置的数据
#### 这个特性的实现形式？
1.调用了 现有的 stopAnimation  animation 函数实现
2.emit 'mouseover' 事件
#### 是否愿意为此特性提交PR？
是

**Comment by jiaming743** [comment]
已合并
