### ISSUE TITLE
轮播表 config.data发生改变后不能及时更新

### ISSUE THREAD

**Issue by kagari2613** [DataV-Team/DataV#98]
## Feature request
实时响应data数据更新
#### 这个特性解决了什么问题？
数据变化后动态刷新列表
#### 这个特性的实现形式？
config.data=newData,视图变化

**Comment by jiaming743** [comment]
[datav](http://datav.jiaminghi/com)文档第一页就说了，暂时没有做深度监听，按照示例更新数据即可

**Comment by kagari2613** [comment]
> [datav](http://datav.jiaminghi.com)文档第一页就说了，暂时没有做深度监听，按照示例更新数据即可

ok，多谢
